

export const destinations = [
    {
        id: 0,
        name: "Mercure",
        images: "/img/assets/destination/mercure.png",
        description: "Mercure est la plus petite des planètes du Système Solaire, ainsi que la plus proche du Soleil. Sa surface est caractérisée par de nombreux cratères, résultats d’impacts de météorites dût a son manque d'atmosphère",
        distance: "57 910 000 km",
        travel: "6,5 ans",
        diamètre: "4 878 km",
        périodeRévolution: "88 jours",
        rotation: "58,60 jours",
        températureMoy: "",
        températureMin: "-183°C",
        températureMax: "427°C",
        atmosphère: "non",
        gravité: "3.701 m/s2",
        infoGravite: "20 fois plus petite que sur Terre",
        satellites: "0",
    },
    {
        id: 1,
        name: "Vénus",
        images: "/img/assets/destination/Venus.png",
        description: "Vénus est aussi appelée l'étoile du Berger, car étant proche du Soleil, elle se couche juste après lui ou se lève juste avant ce dernier.Ce monde s’avère parsemé de centaines de volcans, dont 167 géants. il y fait plus de 460 °C, aussi bien le jour que la nuit. Ceci est à cause de son atmosphère épaisse opaque d'une cinquantaine de kilomètres qui provoque un effet de serre et retient toute la chaleur reçue.",
        distance: "108 200 000 km",
        travel: "15 mois",
        diamètre: "12 102 km",
        périodeRévolution: "224,7 jours",
        rotation: "243 jours",
        températureMoy: "470°C",
        températureMin: "",
        températureMax: "",
        atmosphère: "Dioxyde de carbonne CO2, Azote N2",
        gravité: "10,44 m/s2",
        infoGravite: "un peu plus petite que sur Terre",
        satellites: "0",
    },
    {
        id: 2,
        name: "Terre",
        images: "/img/assets/destination/earth.png",
        description: "La Terre, astre duquel nous sommes seulement l’une des innombrables émanations. Seul astre connu à posséder une biosphère, à abriter la vie. La Terre est un microscosme d’une complexité sans analogue ailleurs dans le cosmos. Depuis peu dans son histoire, les humains sont devenus le principal agent de changement à sa surface, plus que l’eau, le vent ou les volcans. Le milieu du 20ème siècle marque le début de l’exploration spatiale, l’envoi de sondes robotiques et d’astronautes en orbite ou sur la Lune, 70,90 % de sa surface est occupée par les mers et seulement 29,10 % par les cinq continents.",
        distance: "149 600 000 km",
        travel: "",
        diamètre: "12 742 km",
        périodeRévolution: "365,25 jours",
        rotation: "23h 59min 06s",
        températureMoy: "15 °C",
        températureMin: "-93,2 °C",
        températureMax: "56,7 °C",
        atmosphère: "Azote N2, Oxygène O2, Argon Ar, Eau H2O, Dioxyde de carbone CO2",
        gravité: "9,80 m/s2",
        infoGravite: "on vie dessus que sur Terre",
        satellites: "la Lune",
    },
    {
        id: 3,
        name: "Mars",
        images: "/img/assets/destination/mars.png",
        description: "Mars est la mieux connue et la moins inhospitalière des planètes du Système Solaire. t son atmosphère y est très ténue mais existante. La Planète Rouge doit sa couleur caractéristique à l’oxyde de fer (la rouille)",
        distance: "227 940 000 km",
        travel: "7 mois",
        diamètre: "6 786 km",
        périodeRévolution: "686,9 jours",
        rotation: "1,259 jours",
        températureMoy: "-53 °C",
        températureMin: "-143 °C",
        températureMax: "32 °C",
        atmosphère: "Dioxyde de carbone CO2, Azote N2, Oxygène O2, Argon Ar, Monoxyde de carbone CO",
        gravité: "3,711 m/s2",
        infoGravite: "10 fois plus petite que sur Terre",
        satellites: "Phobos, Deimos",
    },
    {
        id: 4,
        name: "Jupiter",
        images: "/img/assets/destination/jupiter.png",
        description: "Jupiter est la plus grande des planètes du Système Solaire. La masse de ce colosse est deux fois-et-demie la masse de toutes les autres planètes mises ensemble. Étant une planète gazeuse, sa surface est caractérisée par des bandes nuageuses composées d’ammoniac. Quatre satellites naturels, identifiés par Galilée lui-même, sont notables : en ordre de grandeur, Ganymède, Callisto, Io et Europe. La fameuse Grande Tache Rouge de Jupiter est un cyclone qui dure depuis possiblement plus de 300 ans, avec des vents violents de 500 km/h.",
        distance: "778 300 00 km",
        travel: "6 ans",
        diamètre: "142 984 km",
        périodeRévolution: "11,8 ans",
        rotation: "09h 55min",
        températureMoy: "",
        températureMin: "-153°C (partie extérieur)",
        températureMax: "",
        atmosphère: "Hydrogène H, Hélium He",
        gravité: "24,79 m/s2",
        infoGravite: "318 fois plus grande que sur Terre",
        satellites: "69 en totalité dont Lo, Europe, Ganymède, Callisto, Métis, Adrassté, Thébé, Amalhtée",
    },
    {
        id: 5,
        name: "Saturne",
        images: "/img/assets/destination/saturn.png",
        description: "Saturne, plus lointaine planète connue par les Anciens, est le deuxième géant du Système Solaire, après Jupiter. Le nom de cet astre célèbre évoque immédiatement son spectaculaire système d’anneaux. Ces structures sont constituées de cristaux d’eau et de poussières. e s’étendent sur plus de 400 000 kilomètres, ils ne dépassent cependant pas 1 km en épaisseur.",
        distance: "1 428 960 km",
        travel: "7 ans",
        diamètre: "120 536 km",
        périodeRévolution: "29,5 ans",
        rotation: "10,6 heures",
        températureMoy: "",
        températureMin: "-183°C (partie extérieur)",
        températureMax: "",
        atmosphère: "Hydrogène H, Hélium He",
        gravité: "10,44 m/s2",
        infoGravite: "95 fois plus grande que sur Terre",
        satellites: "69 dont Titan, Télesto, Calypso et Atlas",
    },
    {
        id: 6,
        name: "Uranus",
        images: "/img/assets/destination/uranus2.png",
        description: "Uranus est une géante gazeuse dont le diamètre équivaut à quatre fois celui de la Terre. Elle fut découverte en 1781 par William Herschel. Uranus possède la plus froide atmosphère du Système Solaire, ce qui lui vaut d’être, avec Neptune, une « géante glacée ». L’axe de rotation d’Uranus est de 98˚ par rapport au plan du Système Solaire. Cela pourrait être dû à une collision cataclysmique survenue lors des grands bombardements. Neuf anneaux étroits ont été découverts, grâce à l'occultation d'une étoile.",
        distance: "2 870 990 000 km",
        travel: "8,5 ans",
        diamètre: "51 118 km",
        périodeRévolution: "84 ans",
        rotation: "18 heures",
        températureMoy: "",
        températureMin: "-216°C",
        températureMax: "",
        atmosphère: "Hydrogène H, Hélium He, Méthane CH₄ ...",
        gravité: "8,87 m/s2",
        infoGravite: "14 fois plus grande que sur Terre",
        satellites: "27, dont Titania, Oberon, Cupid et Puck",
    },
    {
        id: 7,
        name: "Neptune",
        images: "/img/assets/destination/Neptune.png",
        description: "Neptune est légèrement plus petite et cependant plus massive qu’Uranus. Sa couleur bleutée serait due à la présence atmosphérique de méthane. Fait peu ordinaire, sa découverte est attribuable à des prédictions mathématiques déduites de l’orbite d’Uranus plutôt qu’à des observations régulières. Neptune est la plus lointaine des planètes solaires depuis 2006, date à laquelle Pluton fut classée en tant que « planète naine ». Les vents violents pouvant aller jusqu’à 2000 km/h.",
        distance: "4 497 070 000 km",
        travel: "12,5 ans",
        diamètre: "49 520 km",
        périodeRévolution: "164 ans 323 jours",
        rotation: "16h 06 min",
        températureMoy: "",
        températureMin: "-226°C",
        températureMax: "",
        atmosphère: "Hydrogène H, Hélium He, Méthane CH₄ ...",
        gravité: "11,15 m/s2",
        infoGravite: "17 fois plus grande que sur Terre",
        satellites: "14, dont Triton, Néréide, Galatée et Hippocampe",
    },
    {
        id: 8,
        name: "Titan (lune de Saturne)",
        images: "/img/assets/destination/Titan.png",
        description: "Titan est le plus grand satellite de Saturne. Il a été découvert en 1955 par Huygens Il s’agit du seul satellite connu à posséder une atmosphère dense. Titan est principalement composé d’eau sous forme glacée et de roches. Son épaisse atmosphère a longtemps empêché l’observation de sa surface jusqu’à l’arrivée de la mission Cassini-Huygens en 2004, laquelle a permis la découverte de lacs d’hydrocarbures liquides dans les régions polaires du satellite. Le climat comprend des vents et de la pluie de méthane. Le satellite est cité comme un possible hébergeur de vie extraterrestre microbienne ou, au moins, comme un environnement prébiotique riche en chimie organique complexe. Certains chercheurs suggèrent qu’un possible océan souterrain pourrait servir d’environnement favorable à la vie.",
        distance: "1 222 000 km de Saturne",
        travel: "7 ans",
        diamètre: "5 150 km",
        périodeRévolution: "15,95 jours",
        rotation: "15,95 jours",
        températureMoy: "-179 °C",
        températureMin: "-201 °C",
        températureMax: "",
        atmosphère: "Diazote, Méthane, Ethane",
        gravité: "1,428 m/s²",
        infoGravite: "largement inférieure à celle de la Terre",
        satellites: "Plus d'infos",
    }
]




